//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drawer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drawer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Drawer 的本地化字符串。
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YuXiang Drawer 的本地化字符串。
        /// </summary>
        internal static string app_whole_name {
            get {
                return ResourceManager.GetString("app_whole_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Selected: {0} 的本地化字符串。
        /// </summary>
        internal static string bar_selected {
            get {
                return ResourceManager.GetString("bar_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total: {0} 的本地化字符串。
        /// </summary>
        internal static string bar_total {
            get {
                return ResourceManager.GetString("bar_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string button_clear {
            get {
                return ResourceManager.GetString("button_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string button_export {
            get {
                return ResourceManager.GetString("button_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string button_find {
            get {
                return ResourceManager.GetString("button_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string button_help {
            get {
                return ResourceManager.GetString("button_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string button_import {
            get {
                return ResourceManager.GetString("button_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string button_password {
            get {
                return ResourceManager.GetString("button_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 YuXiang Drawer: Random Name Picker{0}Version 4.0{1}Author YuXiang187{2}The initial password for the &quot;Edit&quot; function is 123456.{3}The software supports setting a background image, please place the image in the root directory of this software.{4}The recommended image size is 450x250 (9:5), with one of the following names:{5}- background.jpg{6}- background.jpeg{7}- background.png{8}- background.bmp 的本地化字符串。
        /// </summary>
        internal static string dialog_about {
            get {
                return ResourceManager.GetString("dialog_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string dialog_content_is_empty {
            get {
                return ResourceManager.GetString("dialog_content_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard all content? 的本地化字符串。
        /// </summary>
        internal static string dialog_discard_content {
            get {
                return ResourceManager.GetString("dialog_discard_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content of the text file is empty. 的本地化字符串。
        /// </summary>
        internal static string dialog_document_is_empty {
            get {
                return ResourceManager.GetString("dialog_document_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The syntax for editing the list is:{0}Name1,Name2,Name3,Name4,Name5,...{1}Note: The separator is an English comma. 的本地化字符串。
        /// </summary>
        internal static string dialog_editor_help {
            get {
                return ResourceManager.GetString("dialog_editor_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password:  的本地化字符串。
        /// </summary>
        internal static string dialog_enter_password {
            get {
                return ResourceManager.GetString("dialog_enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plain text{0} 的本地化字符串。
        /// </summary>
        internal static string dialog_File_filter {
            get {
                return ResourceManager.GetString("dialog_File_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find completed. 的本地化字符串。
        /// </summary>
        internal static string dialog_find_complete {
            get {
                return ResourceManager.GetString("dialog_find_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear content? 的本地化字符串。
        /// </summary>
        internal static string dialog_is_clear_content {
            get {
                return ResourceManager.GetString("dialog_is_clear_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not include the English comma &quot;,&quot;. 的本地化字符串。
        /// </summary>
        internal static string dialog_no_english_comma {
            get {
                return ResourceManager.GetString("dialog_no_english_comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password has been changed to: {0}{1} 的本地化字符串。
        /// </summary>
        internal static string dialog_password_changed {
            get {
                return ResourceManager.GetString("dialog_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string dialog_password_empty_warn {
            get {
                return ResourceManager.GetString("dialog_password_empty_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We&apos;ve detected that you&apos;re using the initial password.{0}To ensure that the list content is not maliciously tampered with, please change your password promptly using the &quot;Password&quot; function. 的本地化字符串。
        /// </summary>
        internal static string dialog_password_low_warning {
            get {
                return ResourceManager.GetString("dialog_password_low_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password incorrect. 的本地化字符串。
        /// </summary>
        internal static string dialog_password_wrong {
            get {
                return ResourceManager.GetString("dialog_password_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient permissions, unable to create or delete auto-start tasks.{0}{1} 的本地化字符串。
        /// </summary>
        internal static string dialog_permission_error {
            get {
                return ResourceManager.GetString("dialog_permission_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The statistics are as follows.{0}Number of draws: {1}{2}List of names drawn: {3} 的本地化字符串。
        /// </summary>
        internal static string dialog_statistics {
            get {
                return ResourceManager.GetString("dialog_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Segoe UI 的本地化字符串。
        /// </summary>
        internal static string font_name {
            get {
                return ResourceManager.GetString("font_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string menu_close {
            get {
                return ResourceManager.GetString("menu_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl key 的本地化字符串。
        /// </summary>
        internal static string menu_ctrl {
            get {
                return ResourceManager.GetString("menu_ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float window 的本地化字符串。
        /// </summary>
        internal static string menu_float {
            get {
                return ResourceManager.GetString("menu_float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string menu_move {
            get {
                return ResourceManager.GetString("menu_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string menu_pause {
            get {
                return ResourceManager.GetString("menu_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start on boot 的本地化字符串。
        /// </summary>
        internal static string menu_start_on_boot {
            get {
                return ResourceManager.GetString("menu_start_on_boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        internal static string menu_statistics {
            get {
                return ResourceManager.GetString("menu_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 About YuXiang Drawer 的本地化字符串。
        /// </summary>
        internal static string title_about {
            get {
                return ResourceManager.GetString("title_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password 的本地化字符串。
        /// </summary>
        internal static string title_change_password {
            get {
                return ResourceManager.GetString("title_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string title_error {
            get {
                return ResourceManager.GetString("title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon tray_run {
            get {
                object obj = ResourceManager.GetObject("tray_run", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon tray_stop {
            get {
                object obj = ResourceManager.GetObject("tray_stop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
